apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ovsdbutil-injector-webhook-deployment
  labels:
    app: ovsdbutil-injector
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ovsdbutil-injector
    spec:
      containers:
        - name: ovsdbutil-injector
          image: gopinatht/cord-ovsdb-injector:latest
          imagePullPolicy: Always
          args:
            - -sidecarCfgFile=/etc/webhook/config/sidecarconfig.yaml
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
            - name: webhook-config
              mountPath: /etc/webhook/config
      volumes:
        - name: webhook-certs
          secret:
            secretName: ovsdbutil-injector-webhook-certs
        - name: webhook-config
          configMap:
            name: ovsdbutil-injector-webhook-configmap
