apiVersion: v1
kind: Service
metadata:
  name: ovsdbutil-injector-webhook-svc
  labels:
    app: ovsdbutil-injector
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: ovsdbutil-injector
